version: "3.8"

volumes:
  db-data:

networks:
  instavote:
    driver: bridge

services:
  redis:
    image: redis:alpine
    networks:
      - instavote

  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - instavote
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  worker:
    image: ilosaurus/worker:latest
    build: ./worker
    depends_on:
      - redis
      - db
    networks:
      - instavote

  vote:
    image: ilosaurus/vote:latest
    build: ./vote
    ports:
      - 5000:80
    depends_on:
      - redis
    networks:
      - instavote

  result:
    image: ilosaurus/result:latest
    build: ./result
    ports:
      - 5100:4000
    depends_on:
      - db
    networks:
      - instavote
